
version: '3'
services:
 mysqldb:
  image: mysql:8.0.1
  environment:
   MYSQL_DATABASE: 'dev_db'
   MYSQL_USER: 'dev_user'
   MYSQL_PASSWORD: 'dev_pass'
   MYSQL_ROOT_PASSWORD: 'root_pass'
  ports:
   - "3306:3306"
  volumes:
   - "/Users/rootchile/data-docker/mysql-data:/var/lib/mysql"
 phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    links:
      - mysqldb:db